### ISSUE TITLE
K. Michaelian's paper

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework7G3#1]
for your info, the paper mentioned is available at
https://pubs-aip-org.gate.lib.buffalo.edu/aapt/ajp/article/66/3/231/1044856/Evolving-few-ion-clusters-of-Na-and-Cl

**Comment by poojashresthacode** [comment]
Thanks

**Comment by Pranjal-Srivastava-2023** [comment]
Thanks @LinxuanHu

**Comment by JustinJaniszewski** [comment]
Thanks
