### ISSUE TITLE
Maintainer Selection

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework7G3#13]
Hi guys, if there is no problem, can I be the maintainer for this group? @Pranjal-Srivastava-2023 @JustinJaniszewski

**Comment by Pranjal-Srivastava-2023** [comment]
Hi, @poojashresthacode since you were the maintainer for HW5 I think I would like to be the maintainer this time.

**Comment by poojashresthacode** [comment]
It's okay if you want. No worries.
