### ISSUE TITLE
Potential formula confusion

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G3#18]
The ion-ion potential in K.Michaelian paper is:
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/2763ce21-6932-48e6-a6ab-dd13be0ce300)
and the one found in the [Compphys minmax](https://github.com/ubsuny/CompPhys/blob/main/MinMax/nacl.ipynb) is:
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/17a67a06-b958-4c8b-87ca-8fa29b15f092)
 
and in the paper, the potential formula is referenced to:
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/4e566993-33cc-464c-b43a-d2e42140a19e)
For this homework, which formula should we follow?

**Comment by pratibha77118** [comment]
@reshnashrestha have you got the answer for potential energy formula to be used. I think the formula are basically same, the only difference is that the negative ion include additional repulsive Pauli energy.

**Comment by reshnashrestha** [comment]
Yeah we should be using the one used in the CompPhys
