### ISSUE TITLE
Size of the box!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework7G3#20]
I have chosen a planar rectangle as one of the 7 configurations, how would we expect to assign the values of a and b (a=length and b=width)? Are we allowed to choose randomly? Because there are no specific values for these terms in the paper?

**I will appreciated your responses.**

**Comment by pratibha77118** [comment]
I am going through the same issues. How to chose the position of ions?

**Comment by poojashresthacode** [comment]
I think we can choose any size of the box, as your wish.

**Comment by pratibha77118** [comment]
@poojashresthacode how come we implement it for different configuration then?

**Comment by tirthbha** [comment]
@poojashresthacode @pratibha77118 
Guys, I got to know that choosing any appropriate values of a and b, randomly, will not affect the potential energy value. The difference is only that the optimization algorithm will requires more number of steps to minimize the system with the large box size.
