### ISSUE TITLE
progress of task.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework7G3#21]
Hi @JustinJaniszewski and @Pranjal-Srivastava-2023 , how's your homework going on? Have you got any idea on how to get the initial positions?

**Comment by pratibha77118** [comment]
@poojashresthacode have you got any idea on how to assign the initial values for different configuration?

**Comment by JustinJaniszewski** [comment]
Sorry I have not checked it out yet.

**Comment by Pranjal-Srivastava-2023** [comment]
The milestone has been created to track the progress.
