### ISSUE TITLE
Structure of Tetramers Configuration

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework7G3#22]
Hi all,
 Do we have to know the structure of tetramer configurations and search for the position of Na and Cl ion to be used for optimization. For different structure, what is the difference that we have to do to implement the code. Paper shows that the binding energy per ions for given configurations are different, so how we approach to get that value?

**Comment by poojashresthacode** [comment]
Yeah, you are right. Also, the main difference is the position of the ions.
