### ISSUE TITLE
Configuration choosen.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework7G3#23]
Hi @Pranjal-Srivastava-2023 @JustinJaniszewski , I chose configuration with binding energy -6.9788 ad -6.7470 (the first ad last figure)

**Comment by poojashresthacode** [comment]
Hi @Pranjal-Srivastava-2023 I was about to create pull request, but it seems that cubic structure is already there. so , can two from the group can do the same structure?

**Comment by Pranjal-Srivastava-2023** [comment]
I guess you can still send the merge request, it will be interesting to compare.

**Comment by poojashresthacode** [comment]
Sure.
________________________________
