### ISSUE TITLE
Why doesn't the Compphys notebook show any interactive plot? 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework7G3#26]
<img width="1051" alt="Screenshot 2023-11-30 at 12 03 18 AM" src="https://github.com/ubsuny/23-Homework7G3/assets/66480280/acb9dd53-2cb0-4c8a-b569-b17480d8200a">

**Comment by uarif** [comment]
I think the 3D plotting is not properly installed. Play with it a little and it will work. it happened to me too, then I fixed it. @Mosaddeq107

**Comment by poojashresthacode** [comment]
@ I have that problem too. How did you fix it @uarif

**Comment by poojashresthacode** [comment]
I have solved the problem. https://github.com/ubsuny/23-Homework7G5/pull/40

**Comment by uarif** [comment]
Did you figure out? @Mosaddeq107 . If not I can share my part of the code which works and you can see what is it working for me,

**Comment by JustinJaniszewski** [comment]
> I have solved the problem. [ubsuny/23-Homework7G5#40](https://github.com/ubsuny/23-Homework7G5/pull/40)

what exactly is the solution to the problem?

**Comment by uarif** [comment]
I think adding these lines should resolve the prob. 
%matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

**Comment by Pranjal-Srivastava-2023** [comment]
It works for me.

**Comment by uarif** [comment]
Yes, I guess it doesn't work for some people but there is a solution
