### ISSUE TITLE
cubic structur.

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework7G3#27]
Who took cubic structure in your group? I am facing an issue, **nan"divide by zero encountered in divide"** for potential calculations. I took those 8 indices, and they are all, (a,0,0), (0,0,a), etc. and I considered all indices to be at most "a" apart. Did I take those indices wrong, or am I missing something? 
Thank you.

**Comment by poojashresthacode** [comment]
I am surprised, how is it possible.

**Comment by poojashresthacode** [comment]
Yeah..i was also thinking same. I figured it out now it's 28. Thankyou
________________________________

**Comment by uarif** [comment]
Then it means we are on the same page, so I also don't have to worry about it 😁. Good luck

**Comment by Pranjal-Srivastava-2023** [comment]
I did not get this error.

**Comment by uarif** [comment]
yes, that is resolved. than you
