### ISSUE TITLE
Are bond length same for all the structures between Na and Cl ions?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework7G3#35]

**Comment by tirthbha** [comment]
@s4il3sh Depends on the configuration you chosen. For the distorted rectangle, the bond length is different.

**Comment by s4il3sh** [comment]
ok so how do we find this information? It's not given in the paper.

**Comment by Pranjal-Srivastava-2023** [comment]
We need to make the best guess using trial and error. If you have a better strategy please share.
