### ISSUE TITLE
Have you selected configurations? 

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework7G3#48]
@poojashresthacode I am going to go ahead and start working on some configurations. I dont see any issues of you picking any yet but I thought I would ask anyway since there are a lot of issues right now and I could have missed it. Have you selected any? If so, which ones?

**Comment by poojashresthacode** [comment]
I have already done for the cubic structure and the (seventh) last structure. I don't know what it is called.

**Comment by Pranjal-Srivastava-2023** [comment]
@poojashresthacode I already did the cubic structure.
