### ISSUE TITLE
rectangle.ipynb doesn't print the optimized potential.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework7G3#59]

**Comment by poojashresthacode** [comment]
what's the error message?

**Comment by Pranjal-Srivastava-2023** [comment]
There is no error message. The code is missing two lines:

res = scipy.optimize.minimize(fun=cluster, x0=vals_init, tol=1e-3, method="BFGS")
cluster.set_vals(res.x) # Update the class instance with the final optimized positions

**Comment by JustinJaniszewski** [comment]
yes but I dont understand that. If I do that, the shape is all weird when plotting

**Comment by JustinJaniszewski** [comment]
I think I understand now. Thank you for letting me know.
