### ISSUE TITLE
Cubic Rectangular Configurations

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G3#63]
I have completed the over all tasks under this topic and the my work is summarized in:
[cubic_rectangular_configurations.md](https://github.com/ubsuny/23-Homework7G4/blob/main/cubic_rectangular_configurations.md)

**Comment by Pranjal-Srivastava-2023** [comment]
Thanks for sharing. It's a very detailed explanation.

**Comment by reshnashrestha** [comment]
Well thank you
